---
language: ruby
sudo: required
dist: trusty
cache:
  bundler: true
  directories:
    - .deploy
    - bower_components
    - node_modules

before_cache:
  - rm -rf ./node_modules/.bin/which

before_install:
  - nvm install
  - 'echo ''gem: --no-document'' > ~/.gemrc'
  - gem install bundler

before_script:
  - npm install

after_success:
  - ./.travis/deploy.sh
