---
language: ruby
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules
sudo: false

before_script:
  - nvm install
  - npm install

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'
