---
language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - bower_components
    - node_modules

before_install:
  - gem install bundler
  - nvm install
  - 'echo ''gem: --no-document'' > ~/.gemrc'

before_script:
  - npm install

after_success:
  - ./.travis/deploy.sh
