source: ./src
destination: ./dist

include:
  - .nojekyll

gems:
  - jekyll-assets

highlighter: none

kramdown:
  input: GFM

assets:
  sources:
    - _assets/bower_components

livereload:
  port: 35729
