source: ./src
destination: ./dist

include:
  - .nojekyll

gems:
  - jekyll-assets
  - jekyll-gist
  - jekyll/scholar

highlighter: false
markdown: redcarpet
redcarpet:
  extensions:
    - disable_indented_code_blocks
    - no_intra_emphasis
    - smart
    - space_after_headers
    - tables

assets:
  sources:
    - _assets/bower_components

livereload:
  port: 35729

scholar:
  source: _assets/bower_components/references
  reference_tagname: cite
  bibtex_filters:
    - latex
    - markdown

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
