name: Evan Sosenko
markdown: redcarpet
pygments: true

exclude: [ 'CHANGELOG.md', 'LICENSE.txt', 'README.md', 'VERSION', 'Gemfile.lock', 'Gemfile', 'Rakefile' ]

assets:
  compress:
    css: sass
    js: uglifier

google_analytics: UA-19631381-1
piwik: evansosenko.com/piwik/

:deploy:
  :protocol: :rsync
  :server: ssh.evansosenko.com
  :user: webmaster
  :port: 50000
  :path: /usr/local/www/vhosts/evansosenko.com/htdocs/
