source: ./src
destination: ./dist

include:
  - .nojekyll

gems:
  - jekyll-assets

markdown: redcarpet
redcarpet:
  extensions:
    - disable_indented_code_blocks
    - no_intra_emphasis
    - smart
    - space_after_headers
    - tables

assets:
  sources:
    - _assets/bower_components

livereload:
  port: 35729
