---
title: evansosenko.com
description: >-
  Personal site and blog of Evan Sosenko:
  Ph.D. physics student, developer, gamer, and tinkerer.
name: evansosenko.com
locale: en_US
image: ~
image_asset: ~
color: ~
keywords:
  - jekyll

twitter:
  site: ~
  creator: ~
  card: ~
