---
title: evansosenko.com
description: >-
  Personal site and blog of Evan Sosenko:
  Physics Ph.D. candidate, developer, gamer, and tinkerer.
name: evansosenko.com
locale: en_US
image: ~
image_asset: ~
color: ~
keywords:
  - physics
  - math
  - code
  - development
  - web development
  - blog
  - personal

twitter:
  card: summary
  site: '@evansosenko'
  creator: '@evansosenko'
